apiVersion: stash.appscode.com/v1beta1
kind: BackupSession
metadata:
  name: sample-elasticsearch-instant-backup
  namespace: demo
spec:
  invoker:
    apiGroup: stash.appscode.com
    kind: BackupConfiguration
    name: sample-es-backup