apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: demo-postgres
  namespace: demo
spec:
  # replicas: 3
  # standbyMode: Hot
  clientAuthMode: md5
  version: "13.2"
  storageType: Durable
  podTemplate:
    spec:
      resources:
        limits:
          cpu: 250m
          memory: 300Mi
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut