apiVersion: kubedb.com/v1alpha2
kind: Elasticsearch
metadata:
  name: es-quickstart
  namespace: demo
spec:
  kernelSettings: {}
  version: xpack-7.9.1-v1
  enableSSL: true
  replicas: 3
  storageType: Durable
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  podTemplate: 
    spec:
      securityContext: {}
      containerSecurityContext: 
        runAsUser: 1000610000
  #       runAsGroup: 1000610000
  terminationPolicy: WipeOut